pipeline {
    agent any
    environment {
        DOCKER_CONTEXT = "desktop-linux" // Cambia esto a tu contexto si es otro
    }
    stages {
        stage("Build Frontend") {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Sof-1215/Lab1Tingeso']])
                dir("TingesoFrontend") {
                    bat "npm install"
                    bat "npm run build"
                }
            }
        }
        stage("Build and Push Docker Image") {
            steps {
                dir("TingesoFrontend") {
                    script {
                        withDockerRegistry(credentialsId: 'docker-credentials') {
                            bat "docker --context %DOCKER_CONTEXT% build -t sof1215/tingesofrontend ."
                            bat "docker --context %DOCKER_CONTEXT% push sof1215/tingesofrontend"
                        }
                    }                    
                }
            }
        }
    }
}
